// Package prov records where a value came from, in W3C PROV-O terms: an
// Entity was generated by an Activity, which was run by an Agent. Keeping
// the vocabulary means the record joins other PROV data without translation.
package prov

import "time"

type Entity struct {
	ID          string
	GeneratedBy string // Activity.ID
	DerivedFrom []string
}

type Activity struct {
	ID    string
	Kind  string
	Agent string // Agent.ID
	Start time.Time
	End   time.Time
	Used  []string // Entity.ID
}

type Agent struct {
	ID   string
	Kind string // person, software, organization
}

// Log is the append-only record the three types are written to.
type Log interface {
	Entity(Entity) error
	Activity(Activity) error
	Agent(Agent) error
	Trace(id string) ([]Activity, error)
}
