// Package prov records where a value came from, in W3C PROV-O terms: an
// Entity was generated by an Activity, which was run by an Agent. Keeping
// the vocabulary means the record joins other PROV data without translation.
package prov

import "time"

// Entity is a thing whose origin is being recorded: a document, a chunk, a
// triple, a graph. It names the activity that produced it and the entities it
// was derived from, so a claim can be walked back to its sources.
type Entity struct {
	ID          string
	GeneratedBy string // Activity.ID
	DerivedFrom []string
}

// Activity is something that happened over an interval and produced entities:
// an ingest, an extraction, a merge. Used lists what it read.
type Activity struct {
	ID    string
	Kind  string
	Agent string // Agent.ID
	Start time.Time
	End   time.Time
	Used  []string // Entity.ID
}

// Agent is whoever bears responsibility for an activity — a person, a program,
// or the organization either acts for.
type Agent struct {
	ID   string
	Kind string // person, software, organization
}

// Log is the append-only record the three types are written to.
type Log interface {
	Entity(Entity) error
	Activity(Activity) error
	Agent(Agent) error
	Trace(id string) ([]Activity, error)
}
